<script setup lang="ts">
// VLM Direct Analysis dashboard — independent from the low-budget
// sampler/pipeline mode. The operator uploads a video, it plays directly in
// the browser, and the VLM's risky-second detections are shown as red
// markers on the timeline plus a filterable/sortable event list. There is
// no live VLM-direct backend yet, so events are generated by
// useVlmMockData.ts (scaled to the actual uploaded video's duration) —
// every component below is wired the same way it would be for a real API,
// so the mock generator is the only thing to swap out later.
import { generateMockEvents, summarize, riskLevelCounts, eventTypeCounts } from '~/composables/useVlmMockData'

const videoUrl = ref<string | null>(null)
const fileName = ref<string | null>(null)
const duration = ref(0)
const currentTime = ref(0)
const activeEventId = ref<string | null>(null)

function onFileSelected(file: File) {
  if (videoUrl.value) URL.revokeObjectURL(videoUrl.value)
  videoUrl.value = URL.createObjectURL(file)
  fileName.value = file.name
  duration.value = 0
  currentTime.value = 0
  activeEventId.value = null
}

onBeforeUnmount(() => {
  if (videoUrl.value) URL.revokeObjectURL(videoUrl.value)
})

const events = computed(() => generateMockEvents(duration.value))
const summary = computed(() => summarize(events.value))
const riskCounts = computed(() => riskLevelCounts(events.value))
const typeCounts = computed(() => eventTypeCounts(events.value))

function onSelectEvent(id: string) {
  activeEventId.value = id
}
</script>

<template>
  <div class="max-w-7xl mx-auto px-6 py-6">
    <div class="mb-5 flex flex-wrap items-start justify-between gap-4">
      <div>
        <h2 class="text-xl font-bold tracking-tight text-slate-100">VLM Direct Analysis</h2>
        <p class="mt-1 text-sm text-slate-500">Video doğrudan görsel-dil modeline gönderilerek analiz edilir.</p>
      </div>
    </div>

    <div class="mb-5 rounded-md border border-info/30 bg-info/10 px-4 py-2.5 text-xs text-slate-300">
      Bu ekran örnek/mock analiz verisiyle çalışıyor. Gerçek VLM entegrasyonu tamamlandığında bileşenler canlı sonuçlara bağlanacak.
    </div>

    <div class="mb-5">
      <VlmStatCards :summary="summary" :duration-seconds="duration" />
    </div>

    <div class="grid grid-cols-1 lg:grid-cols-3 gap-5">
      <div class="lg:col-span-2">
        <VlmVideoPanel
          :video-url="videoUrl"
          :file-name="fileName"
          :events="events"
          :duration="duration"
          :current-time="currentTime"
          :active-event-id="activeEventId"
          @file-selected="onFileSelected"
          @time-update="(t: number) => (currentTime = t)"
          @duration-change="(d: number) => (duration = d)"
          @select-event="onSelectEvent"
        />
      </div>
      <div class="lg:col-span-1">
        <VlmRiskCharts :risk-counts="riskCounts" :type-counts="typeCounts" />
      </div>
    </div>

    <div class="mt-5">
      <VlmEventList :events="events" :active-event-id="activeEventId" @select="onSelectEvent" />
    </div>
  </div>
</template>
